#!/usr/bin/env python3
"""Mirror Claude skills into Codex's repository skill directory."""

from __future__ import annotations

import argparse
import filecmp
import shutil
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent
SOURCE_DIR = REPO_ROOT / ".claude" / "skills"
DESTINATION_DIR = REPO_ROOT / ".agents" / "skills"
MARKER_NAME = ".generated-from-claude-skills"
IGNORED_NAMES = {".DS_Store", "__pycache__"}
EXCLUDED_SKILLS = {"share"}


def skill_directories(
    root: Path,
    *,
    excluded: set[str] | None = None,
) -> dict[str, Path]:
    if not root.is_dir():
        raise RuntimeError(f"Skill directory does not exist: {root}")

    excluded = excluded or set()
    skills = {
        child.name: child
        for child in root.iterdir()
        if child.is_dir()
        and child.name not in excluded
        and (child / "SKILL.md").is_file()
    }
    if not skills:
        raise RuntimeError(f"No skills containing SKILL.md were found in {root}")
    return dict(sorted(skills.items()))


def included_files(root: Path) -> dict[Path, Path]:
    files: dict[Path, Path] = {}
    for path in root.rglob("*"):
        relative = path.relative_to(root)
        if any(part in IGNORED_NAMES for part in relative.parts):
            continue
        if path.is_symlink():
            raise RuntimeError(f"Expected a real file or directory, found symlink: {path}")
        if path.is_file() and path.suffix != ".pyc":
            files[relative] = path
    return files


def differences() -> list[str]:
    source_skills = skill_directories(SOURCE_DIR, excluded=EXCLUDED_SKILLS)
    problems: list[str] = []

    if not DESTINATION_DIR.is_dir():
        return [f"Missing directory: {DESTINATION_DIR.relative_to(REPO_ROOT)}"]

    marker = DESTINATION_DIR / MARKER_NAME
    if not marker.is_file():
        problems.append(f"Missing generated-directory marker: {marker.relative_to(REPO_ROOT)}")

    destination_skills = skill_directories(DESTINATION_DIR)
    source_names = set(source_skills)
    destination_names = set(destination_skills)
    for name in sorted(source_names - destination_names):
        problems.append(f"Missing Codex skill copy: {name}")
    for name in sorted(destination_names - source_names):
        problems.append(f"Unexpected Codex skill copy: {name}")

    for name in sorted(source_names & destination_names):
        source_files = included_files(source_skills[name])
        destination_files = included_files(destination_skills[name])
        for relative in sorted(source_files.keys() - destination_files.keys()):
            problems.append(f"Missing from .agents/skills/{name}: {relative}")
        for relative in sorted(destination_files.keys() - source_files.keys()):
            problems.append(f"Extra in .agents/skills/{name}: {relative}")
        for relative in sorted(source_files.keys() & destination_files.keys()):
            if not filecmp.cmp(source_files[relative], destination_files[relative], shallow=False):
                problems.append(f"Content differs: {name}/{relative}")

    return problems


def sync() -> None:
    source_skills = skill_directories(SOURCE_DIR, excluded=EXCLUDED_SKILLS)
    DESTINATION_DIR.parent.mkdir(parents=True, exist_ok=True)

    if DESTINATION_DIR.exists() and not (DESTINATION_DIR / MARKER_NAME).is_file():
        raise RuntimeError(
            f"Refusing to replace {DESTINATION_DIR}: the generated-directory marker is missing."
        )

    temporary = Path(tempfile.mkdtemp(prefix=".skills-", dir=DESTINATION_DIR.parent))
    try:
        for name, source in source_skills.items():
            shutil.copytree(
                source,
                temporary / name,
                copy_function=shutil.copy2,
                ignore=shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc"),
            )
        (temporary / MARKER_NAME).write_text(
            "Generated by `uv run sync_skills.py`; edit .claude/skills instead.\n",
            encoding="utf-8",
        )

        if DESTINATION_DIR.exists():
            shutil.rmtree(DESTINATION_DIR)
        temporary.replace(DESTINATION_DIR)
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Copy canonical .claude/skills into .agents/skills or check that the copies match."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report differences without changing files",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check:
        problems = differences()
        if problems:
            print("Skill copies are out of date:")
            for problem in problems:
                print(f"  - {problem}")
            print("Run: uv run sync_skills.py")
            return 1
        print("Skill copies match .claude/skills.")
        return 0

    sync()
    copied_count = len(skill_directories(SOURCE_DIR, excluded=EXCLUDED_SKILLS))
    print(f"Copied {copied_count} skills into .agents/skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
